# .github/workflows/appservice.yml
name: Backend – App Service
on:
  push: { branches: [main] }
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: { id-token: write, contents: read }
    steps:
      - uses: actions/checkout@v4
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_9A7642E2F142404190FA116E65D47324 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_CD1D3ED8C3094557905B710E8C308399 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_761A07701A1245A5A195E26B2933F6E2 }}
      - name: Deploy to App Service
        uses: azure/webapps-deploy@v3
        with:
          app-name: uberli-secret-backend           # your App Service name (API)
          package: .                                # deploy whole repo (Oryx installs & runs)